# config/zed2i_yaml
# Parameters for Stereolabs zed2i camera
---

/**:
    ros__parameters:

        general:
            camera_model:               'zed2i'
            camera_name:                'zed2i'

        depth:
            min_depth:                  0.3            # Min: 0.2, Max: 3.0 - Default 0.7 - Note: reducing this value wil require more computational power and GPU memory
            max_depth:                  20.0            # Max: 40.0

        pos_tracking:
            imu_fusion:                 true            # enable/disable IMU fusion. When set to false, only the optical odometry will be used.
            publish_imu_tf:             true            # enable/disable the static IMU TF broadcasting

        sensors:
            sensors_image_sync:         false           # Synchronize Sensors messages with latest published video/depth message
            sensors_pub_rate:           200.            # frequency of publishing of sensors data. MAX: 400. - MIN: grab rate
            qos_history:                1               # '1': KEEP_LAST - '2': KEEP_ALL
            qos_depth:                  1               # Queue size if using KEEP_LAST
            qos_reliability:            1               # '1': RELIABLE - '2': BEST_EFFORT -
            qos_durability:             2               # '1': TRANSIENT_LOCAL - '2': VOLATILE

        object_detection:
            od_enabled:                 false           # True to enable Object Detection [only ZED 2]
            confidence_threshold:       50.0            # [DYNAMIC] - Minimum value of the detection confidence of an object [0,100]
            model:                      2               # '0': MULTI_CLASS_BOX - '1': MULTI_CLASS_BOX_ACCURATE - '2': HUMAN_BODY_FAST - '3': HUMAN_BODY_ACCURATE - '4': MULTI_CLASS_BOX_MEDIUM - '5': HUMAN_BODY_MEDIUM - '6': PERSON_HEAD_BOX 
            mc_people:                  true            # [DYNAMIC] - Enable/disable the detection of persons for 'MULTI_CLASS_BOX' and 'MULTI_CLASS_BOX_ACCURATE' models
            mc_vehicle:                 true            # [DYNAMIC] - Enable/disable the detection of vehicles for 'MULTI_CLASS_BOX' and 'MULTI_CLASS_BOX_ACCURATE' models
            mc_bag:                     true            # [DYNAMIC] - Enable/disable the detection of bags for 'MULTI_CLASS_BOX' and 'MULTI_CLASS_BOX_ACCURATE' models
            mc_animal:                  true            # [DYNAMIC] - Enable/disable the detection of animals for 'MULTI_CLASS_BOX' and 'MULTI_CLASS_BOX_ACCURATE' models
            mc_electronics:             true            # [DYNAMIC] - Enable/disable the detection of electronic devices for 'MULTI_CLASS_BOX' and 'MULTI_CLASS_BOX_ACCURATE' models
            mc_fruit_vegetable:         true            # [DYNAMIC] - Enable/disable the detection of fruits and vegetables for 'MULTI_CLASS_BOX' and 'MULTI_CLASS_BOX_ACCURATE' models
            body_fitting:               false           # Enable/disable body fitting for 'HUMAN_BODY_FAST' and 'HUMAN_BODY_ACCURATE' models
            qos_history:                1               # '1': KEEP_LAST - '2': KEEP_ALL
            qos_depth:                  1               # Queue size if using KEEP_LAST
            qos_reliability:            1               # '1': RELIABLE - '2': BEST_EFFORT -
            qos_durability:             2               # '1': TRANSIENT_LOCAL - '2': VOLATILE
