# config/zedxone4k.yaml
# Parameters for Stereolabs ZED X One 4K camera
---
/**:
    ros__parameters:
        general:
          camera_model: 'zedxone4k'
          camera_name: 'zedxone4k' # usually overwritten by launch file
          grab_resolution: 'QHDPLUS' # The native camera grab resolution. 'HD4K', 'HD1200', 'QHDPLUS, 'HD1080', 'SVGA', 'AUTO'
          grab_frame_rate: 30 # ZED SDK internal grabbing rate (HD4K/QHDPLUS: 15 - HD1200/HD1080: 60, 30, 15 - SVGA: 120, 60, 30, 15)

        video:
          enable_hdr: false # When set to true, the camera will be set in HDR mode if the camera model and resolution allows it

