# config/zedxonegs.yaml
# Parameters for Stereolabs ZED X One GS camera
---
/**:
    ros__parameters:
        general:
          camera_model: 'zedxonegs'
          camera_name: 'zedxonegs' # overwritten by launch file
          grab_resolution: 'HD1080' # The native camera grab resolution. 'HD1200', 'HD1080', 'SVGA', 'AUTO'
          grab_frame_rate: 15 # ZED SDK internal grabbing rate (HD1200/HD1080: 60, 30, 15 - SVGA: 120, 60, 30, 15)